version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=240395
      - MYSQL_PASSWORD=240395
      - MYSQL_USER=ecommerceapp
      - MYSQL_DATABASE=full-stack-ecommerce