spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/full-stack-ecommerce?useSSL=false&useUnicode=true
        username: ecommerceapp
        password: ecommerceapp
    flyway:
        enabled: true
        validate-on-migrate: true